### ISSUE TITLE
README file?

### ISSUE THREAD

**Issue by sardaukar** [komplekt17/CintaNotesWeb#1]
Hey, this project looks really interesting!

I managed to install all NPM modules and get the ENV variables needed to boot up the project, but when I go to the browser on the port it's running, I get 

```Cannot GET /```

What am I missing? Here's my `.envrc` file:

```
export DATABASE_NAME=cinta
export DATABASE_USER=username
export DATABASE_PASS=<empty on my local machine>
export HOSTING_URI=localhost
export DATABASE_PORT=5432
export DATABASE_DIALECT=postgres
export NODE_PORT=3000
export TYPE_ENV=production
```

Thanks and keep it up!

**Comment by komplekt17** [comment]
hello, I use env.yaml
development:
  HOSTING_URI: localhost
  SITE_NAME: CintaNotesWeb
  DATABASE_USER: ***
  DATABASE_PASS: ***
  DATABASE_NAME: ***
  DATABASE_DIALECT: mysql
  DATABASE_PORT: 3306
  JWT_KEY: ***
  NODE_PORT: 5000
  TYPE_ENV: development
  SERVICE_HOST: smtp.gmail.com
  SERVICE_USER: k***@gmail.com
  SERVICE_PASS: ***
production:
  HOSTING_URI: ***
  SITE_NAME: CintaNotesWeb
  DATABASE_USER: ***
  DATABASE_PASS: ***
  DATABASE_NAME: ***
  DATABASE_DIALECT: mysql
  DATABASE_PORT: 3306
  JWT_KEY: ***
  NODE_PORT: 8080
  TYPE_ENV: production
  SERVICE_HOST: smtp.gmail.com
  SERVICE_USER: ***@gmail.com
  SERVICE_PASS: ***
